version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tp_api
    ports:
      - '1337:8000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      test: curl -I --fail http://localhost:8000/ || exit 1
      interval: 60s
      timeout: 2s
      retries: 5