services:
  front:
    build:
      context: .
      dockerfile: Dockerfile_front
    image: tp_front
    ports:
      - '3000:3000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  back:
    build:
      context: .
      dockerfile: Dockerfile_api
    image: tp_back
    ports:
      - '5000:8000'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure